#######################################################################################
# Book settings
title                       : Fundamentals of Solid Earth Science  # The title of the book. Will be placed in the left navbar.
author                      : <a href="https://rajmoulik.com/">Pritwiraj (Raj) Moulik</a>  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : "images/logo/logo_avni_color.png"  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**/in-progress", "**/other_files", "features", "README.md",
"scraps","**Key*","**key*","_**.yml",".gitignore"]

# Short description about the book
description: >-
  A brief introduction to Python for scientific applications in the solid Earth sciences.

#######################################################################################
# Repository settings
# Information about where the book exists on the web
repository:
  url                       : https://github.com/globalseismology/avni-courses.solid-earth-fundamentals  # Online location of your book
  path_to_book              : bin  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "cache"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout: 600                        # Execution timeout defines the maximum time (in seconds) each notebook cell is allowed to run for. If the execution takes longer an exception will be raised. The default is 30 seconds, so in cases of long-running cells you may want to specify a higher value. 
  

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/logo_avni_color.ico"  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyter.org">Jupyter</a>  #Will be displayed underneath the left navbar.
  extra_footer              : |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
    </div>

  google_analytics_id       : "G-WB7DQMP0XP"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://portal.globalseismology.org/courses/solid-earth-fundamentals"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

# Plotly rendering
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : "https://geodynamics.org/tools/solidearth"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
   - _bibliography/globalseismology.bib

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
