#######################################################################################
# Book settings
title                       : Fundamentals of Solid Earth Sciences  # The title of the book. Will be placed in the left navbar.
author                      : <a href="https://rajmoulik.com/">Pritwiraj (Raj) Moulik</a>  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : "images/logo/favicon.ico"  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**/in-progress", "**/other_files", "features", "scraps","**Key*","**key*"]

# Short description about the book
description: >-
  A brief introduction to Python for scientific applications in the solid Earth sciences.


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "force"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyter.org">Jupyter</a>  #Will be displayed underneath the left navbar.
  extra_footer              : |
    <div>
    <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 License</a>.
    </div>

#  google_analytics_id       : "UA-86905362-3"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://github.com/pmoulik/GEO203_Fall2022_PSETS"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

# Plotly rendering
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
   - _bibliography/references.bib

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
