#!/bin/sh

#
# jupyter tool
#
# Some notes:
# example.ipynb or a list of notebooks - Ask UCSD 
# anaconda-7 base anaconda environment
# addition al packages from docker - aspect-2.5.0-pre


/usr/bin/invoke_app "$@" -t solidearth \
                         -C "start_jupyterlab -T @tool welcome.ipynb" \
                         -u anaconda-7 \
                         -e CONDA_PREFIX=/apps/share64/debian10/anaconda/anaconda-7/envs/fall2022 \
			 -r none
