# This job installs dependencies, build the book, and pushes it to portal.globalseismology.org
name: Build Jupyter book on self hosted
on: push
jobs:
  deploy-book:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    #  Install Conda Requirements
    - name: Conda Requirements
      run: eval `modulecmd bash load anaconda3`
       && conda config --set channel_priority flexible
       && conda config --append channels conda-forge
       && conda activate fall2022-sef
       
    #  Rsync with SSH 
    #  https://zellwk.com/blog/github-actions-deploy/
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY_DWAR }}
        known_hosts: unnecessary
        if_key_exists: replace
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST_DWAR }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: mkdir -p docs/_build
       && touch docs/_build/touch
       && rsync -r -g --delete-after -v docs/_build/* ${{ secrets.SSH_USER_DWAR }}@${{ secrets.SSH_HOST_DWAR }}:/var/www/portal/drupal/courses/solid-earth-fundamentals/fall2022/

    # Build the book
    - name: Build the book
      run: jupyter-book clean . --all
       && jupyter-book build -W -n --keep-going .
