# This job installs dependencies, build the book, and pushes it to portal.globalseismology.org
name: Build Jupyter book on self hosted
on: push
jobs:
  deploy-book:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    #  Install Conda Requirements
    - name: Conda Requirements
      run: |
         && eval `modulecmd bash load anaconda3`
         && conda config --set channel_priority flexible
         && conda config --append channels conda-forge
         && conda activate fall2022-sef

    # Build the book
    - name: Build the book
      run: |
         && jupyter-book clean . --all
         && jupyter-book build -W -n --keep-going .
